apiVersion: v1
kind: Service
metadata:
  name: client-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: client-deploy
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 31110
    protocol: TCP
