apiVersion: v1
kind: Service
metadata:
  name: express-nodeport
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5002
    nodePort: 31112
    protocol: TCP
  selector:
    app: express-deploy
