# access on localhost 31111
apiVersion: v1
kind: Service
metadata:
  name: flask-nodeport
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5001
    nodePort: 31111
    protocol: TCP
  selector:
    #selector must match template label
    app: flask-deploy
